### ISSUE TITLE
Graphical target does not work

### ISSUE THREAD

**Issue by Irvise** [streaksu/Gloire#9]
Hi,

I rebuilt Gloire anew just now. I wanted to test it an see how far it had gotten.

I have built it from scratch. The process went smoothly. After launching the `gloire.img` image in QEMU using the recommended command (see README), the boot screen takes place. When I select the graphical target, the screen turn black and nothing else happens.

I activated the serialport in QEMU and the following message takes place:

`Starting SLiM ... rtld: DT_SYMBOLIC is not implemented correctly!` The last part is in red and is repeated a couple more times. Then X fails to start citing the lack of `/var/run/slim.auth` file, which was probably deleted by the SLiM process just before citing `slim: Stale lockfile found, removing it`.

Is there a problem with the libc or something else here?

Best regards,
Fer

**Comment by streaksu** [comment]
Hello Irvise,

The DT_SYMBOLIC errors are due to mlibc's dynamic linker not properly supporting that type of sections, but it is otherwise harmless, and should not impact the execution whatsoever.

Could you post the whole serial output? Messages naming `/var/run/slim.auth` should not be fatal on its first run, and the system should be able to boot past the warning. The only way I've gotten it to be an issue is in conjunction with other Xorg stale lock files as part of a dirty poweroff.

**Comment by Irvise** [comment]
Hi Streaksu,

I can confirm that after rebuilding the `.img` file, the system boots as expected :)

I have played around a bit with it and I noticed it is a quite a bit slower compared to when I built it a few months ago. Neofetch now takes a considerable time to run. I have also hanged the GUI/X/XFCE quite a few times (like trying to open the file manager). I suppose it makes sense for the GUI target to be slower as it is now running a full-blown Desktop Environment, but I find it quite unstable...

Nonetheless, great job! I noticed that there is now even a Fortran compiler shipped with the system! \o/

**Comment by streaksu** [comment]
> I can confirm that after rebuilding the .img file, the system boots as expected :)
Neat!

> I have played around a bit with it and I noticed it is a quite a bit slower compared to ...
Yeah, the image's desktop runlevel as you said is quite a bit heavier than with the last image, and I have not made much progress on optimization, I expect to do so in the future, in the meantime, disabling some of the initted services could help.

> Edit: I did a time neofetch and it said that real was 1m and sys was 1m 59s
Neofetch actually is unnaturally slow due to the programs it calls for things like getting screen resolution and used fonts faulting and the script having to go thru fallback after fallback, its something I have meant to fix for a while but since its only neofetch I have put it way back in my TODO list, but I will get around fixing it shortly. Thanks for the heads up!

**Comment by streaksu** [comment]
> I did a time neofetch and it said that real was 1m and sys was 1m 59s

This should have improved with af08c154cb14dbbb7bf1a6e95cdac667fbf055bc, which disables the broken paths until they are broken no more.
